services:
  - type: static
    name: reown-multi-deposit-app
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/((?!assets/).*)"
        destination: "/index.html"


services:
  - type: web
    name: tx-notify
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: node server/index.js
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: ALLOWED_ORIGIN
        value: https://YOUR-STATIC-SITE.onrender.com
